/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mysqlNew.demoMysqlNew;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import com.mysqlNew.demoMysqlNew.User;
import com.mysqlNew.demoMysqlNew.UserRepository;
import java.util.Optional;

/**
 *
 * @author Sistem
 */
@Controller    // This means that this class is a Controller
//@RequestMapping(path="/proyect") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	//@GetMapping(path="/addNewUser") // Map ONLY GET Requests
         @GetMapping({"/","alta"})
         public String prueba(){
             return "pruebaAdd";
         }
         @GetMapping({"/","index"})
         public String principal(){
             return "index";
         }
         @GetMapping(path="/add")
	public String addNewUser (@RequestParam int id,@RequestParam String usu, @RequestParam String nom, @RequestParam String ape
			, @RequestParam String email, @RequestParam String tel) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
                if(id!=0)
                    n.setId(id);
		n.setUserName(usu);
		n.setName(nom);
		n.setLastName(ape);
		n.setEmail(email);
		n.setTelephone(tel);
		userRepository.save(n);
                
		return "index";
	}

	@GetMapping(path="/all")
	public @ResponseBody String getAllUsers() {
		// This returns a JSON or XML with the users
                String encabezado="<div ng-app><div>" +
"            <br><br><a ng-href=\"index\"><h2>Home</h2></a>" +
"            <a ng-href=\"alta\"><h2>Alta</h2></a>" +
"        </div><br>";
                String tabla="<table style=\"width:50%\">" +
                                "  <tr> <th>ID</th>" +
                                "    <th>Usuario</th> " +
                                "    <th>Nombre</th>" +
                                "    <th>Apellidos</th>" +
                                "    <th>Correo</th>" +
                                "    <th>Telefono</th>" +
                                "    <th>Opciones</th>" +
                                "  </tr>";
                                
                User usu=new User();
                Iterable<User> users=userRepository.findAll();
                int fin=0;
                for (User user : users) {
                    tabla+="<tr> "
                                + "<td>"+user.getId()+"</td> "
                                + "<td>"+user.getUserName()+"</td> "
                                + "<td>"+user.getName()+"</td> "
                                + "<td>"+user.getLastName()+"</td> "
                                + "<td>"+user.getEmail()+"</td> "
                                + "<td>"+user.getTelephone()+"</td> "
                                + "<td><a ng-href='update?id={{"+user.getId()+"}}'>Modificar</a><a ng-href='delete?id={{"+user.getId()+"}}'>Eliminar</a> </td> "
                                + "</tr> ";fin++;
                    System.out.println(fin);
                }
                tabla+="</table>";
		return encabezado+tabla+"<script src=\"//ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js\"></script>";
	}
        
        @GetMapping(path="/update")
	public @ResponseBody String updateUser (@RequestParam String id) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
                int id1=Integer.parseInt(id);
		User n = new User();
                n=userRepository.findById(id1).get();
		
		return "<div ng-app='myApp' ng-controller='Controller as cn'>" +
"                   <label>Usuario: <input type=\"text\" ng-model=\"cn.usu\" /></label><br>" +
"                    <label>Nombre: <input type=\"text\" ng-model=\"cn.nom\"  /></label><br>" +
"                    <label>Apellidos: <input type=\"text\" ng-model=\"cn.ape\"  /></label><br>" +
"                    <label>Correo: <input type=\"text\" ng-model=\"cn.email\" /></label><br>" +
"                    <label>Telefono: <input type=\"text\" ng-model=\"cn.tel\" /></label><br>" +
"                    <a ng-href=\"add?id="+id1+"&usu={{cn.usu}}&nom={{cn.nom}}&ape={{cn.ape}}&email={{cn.email}}&tel={{cn.tel}}\"><h2>Registrar</h2></a><br>" +
"                </div>"
                        + "</div>"
                        + "<script src=\"//ajax.googleapis.com/ajax/libs/angularjs/1.2.19/angular.min.js\"></script>"
                        +"<script>var app=angular.module('myApp',[]);"
                        + "app.controller('Controller', function(){"
                        + "var scope=this;"
                        + "scope.usu='"+n.getUserName()+"';"
                        + "scope.nom='"+n.getName()+"';"
                        + "scope.ape='"+n.getLastName()+"';"
                        + "scope.email='"+n.getEmail()+"';"
                        + "scope.tel='"+n.getTelephone()+"';"
                        + "});</script>";
	}
        @GetMapping(path="/delete")
	public String deleteUser (@RequestParam int id) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
                userRepository.deleteById(id);
		return "index";
	}
}
        